### ISSUE TITLE
structured light

### ISSUE THREAD

**Issue by nesquik011** [Maxinger15/3D_Body_Scanner#2]
hello , is it structured light ?

**Comment by Maxinger15** [comment]
Currently the structure is made out of 44x44mm wood. It is not extremely light but I think it is one of the lightest opportunities. I am looking for some new material for the structure which is easier to assembly, possible not very expensive and solid. If you have any ideas which material I can use, don't hesitate to write me :)

**Comment by nesquik011** [comment]
@Maxinger15 we can work on this together :) I got some ideas  , so want to chat on skype ?

**Comment by nesquik011** [comment]
@nesquik011  by the way i meant by structured light is , is it structure light 3D scanner type ? or stereo 
like does it use light patterns by projector

**Comment by Maxinger15** [comment]
Yes we can :D Do you have discord? I don't use skype very much but if you don't have Discord we can use it :)
Skype: kellermeister.maxgrallinger@gmail.com
Discord: Maxinger15#1608

**Comment by Maxinger15** [comment]
Ahh i see what you mean. Currently I don't have a projector. I have only some white LED's for a better picture quallity.

**Comment by nesquik011** [comment]
@Maxinger15 i added you on discord , lets chat :)
